# Generated by Django 6.0.3 on 2026-03-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_section_is_active_student_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
