# Generated by Django 6.0.3 on 2026-03-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_student_contact_number_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
    ]
